# Generated by Django 5.2.1 on 2025-12-23 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_exchangerate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exchangerate',
            options={'verbose_name': 'Курс валют', 'verbose_name_plural': 'Курсы валют'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Сущность пользователя', 'verbose_name_plural': 'Сущности пользователей'},
        ),
    ]
