# Generated by Django 4.2.3 on 2024-11-01 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_factory_options_alter_factory_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorvariation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='color_variant_images/'),
        ),
    ]
