# Generated by Django 4.2.3 on 2024-11-02 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_colorvariation_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='siezes',
            new_name='sizes',
        ),
    ]
