# Generated by Django 4.2.3 on 2024-11-05 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_siezes_product_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='factory',
            name='factory_description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='factory',
            name='factory_name',
            field=models.CharField(max_length=255, verbose_name='Описание'),
        ),
    ]
