# Generated by Django 4.2.3 on 2024-11-27 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=127, verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='ColorVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=50)),
                ('color_code', models.CharField(max_length=7)),
                ('image', models.ImageField(blank=True, null=True, upload_to='color_variant_images/')),
            ],
        ),
        migrations.CreateModel(
            name='FactoryProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factory_name', models.CharField(max_length=255)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('factory_description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcat_name', models.CharField(max_length=127, verbose_name='Подкатегория')),
                ('father', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='factories.category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sizes', models.CharField(blank=True, default=None, max_length=63, null=True, verbose_name='Размеры')),
                ('description', models.TextField(default=None, max_length=255, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('father', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factories.subcategory')),
                ('manufacter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factories.factoryprofile')),
            ],
        ),
    ]
