# Generated by Django 4.2.3 on 2024-11-22 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factory',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='Имя цеховика'),
        ),
    ]
