# Generated by Django 4.2.3 on 2024-11-22 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('factories', '0002_alter_factory_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factory',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='factory_groups', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='factory',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='factory_user_permissions', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='product',
            name='manufacter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factories.factory'),
        ),
    ]
