# Generated by Django 4.2.3 on 2024-11-23 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('factories', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factoryprofile',
            name='factory_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='factoryprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
