# Generated by Django 4.2.3 on 2024-12-05 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('factories', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factoryprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='factory_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='sizes',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Размеры'),
        ),
    ]
