# Generated by Django 4.2.3 on 2025-02-06 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factories', '0003_alter_factoryprofile_user_alter_product_sizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorvariation',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='color_variant_images/'),
        ),
    ]
