# Generated by Django 4.2.3 on 2025-02-17 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factories', '0005_factoryprofile_supplier_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factoryprofile',
            name='supplier_id',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
