# Generated by Django 4.2.3 on 2025-02-18 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factories', '0006_alter_factoryprofile_supplier_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='factoryprofile',
            name='visit_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
