# Generated by Django 4.2.3 on 2025-02-22 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factories', '0008_factoryprofile_imagoco'),
    ]

    operations = [
        migrations.AddField(
            model_name='factoryprofile',
            name='avatar',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='avatars/', verbose_name='Аватарка'),
        ),
    ]
