# Generated by Django 4.2.3 on 2025-03-07 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('factories', '0011_storecategory_product_store_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='SellerCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('seller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='factories.factoryprofile')),
            ],
        ),
    ]
