# Generated by Django 4.2.3 on 2025-03-14 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factories', '0014_remove_promotion_banner_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='back_color',
            field=models.CharField(default='#1976d2', max_length=7),
        ),
        migrations.AddField(
            model_name='promotion',
            name='description_for_factory',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='promotion',
            name='font_color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
        migrations.AddField(
            model_name='promotion',
            name='recommended_drop',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
    ]
