# Generated by Django 5.2.1 on 2025-12-23 06:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factories', '0015_promotion_back_color_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='colorvariation',
            options={'verbose_name': 'Расцветка', 'verbose_name_plural': 'Расцветки'},
        ),
        migrations.AlterModelOptions(
            name='commissionsettings',
            options={'verbose_name': 'Общая комиссия', 'verbose_name_plural': 'Общая комиссия'},
        ),
        migrations.AlterModelOptions(
            name='factoryprofile',
            options={'verbose_name': 'Бокс/Производитель', 'verbose_name_plural': 'Боксы/Производители'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterModelOptions(
            name='productpromotion',
            options={'verbose_name': 'Продукт в акции', 'verbose_name_plural': 'Продукты в акциях'},
        ),
        migrations.AlterModelOptions(
            name='promotion',
            options={'verbose_name': 'Акция', 'verbose_name_plural': 'Акции'},
        ),
        migrations.AlterModelOptions(
            name='promotionapplication',
            options={'verbose_name': 'Заявка на акцию', 'verbose_name_plural': 'Заявки на акции'},
        ),
        migrations.AlterModelOptions(
            name='sellercommission',
            options={'verbose_name': 'Уникальная комиссия', 'verbose_name_plural': 'Уникальные комиссии'},
        ),
        migrations.AlterModelOptions(
            name='storecategory',
            options={'verbose_name': 'Раздел', 'verbose_name_plural': 'Разделы'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'Подкатегория', 'verbose_name_plural': 'Подкатегории'},
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='back_color',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='font_color',
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factories.factoryprofile')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'box')},
            },
        ),
    ]
