# Generated by Django 4.2.3 on 2025-01-08 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='snapshot',
            field=models.JSONField(blank=True, default=dict, verbose_name='Order Snapshot'),
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
