# Generated by Django 4.2.3 on 2025-01-08 08:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_order_snapshot_delete_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='city_delivery',
            field=models.CharField(default=django.utils.timezone.now, max_length=256),
            preserve_default=False,
        ),
    ]
