# Generated by Django 4.2.3 on 2025-01-09 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_alter_order_city_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_snapshot',
            field=models.JSONField(blank=True, default=dict, verbose_name='Customer Snapshot'),
        ),
    ]
