# Generated by Django 4.2.3 on 2025-01-09 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_order_customer_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='detailed_snapshot',
            field=models.JSONField(blank=True, default=dict, verbose_name='Detailed Snapshot'),
        ),
    ]
