# Generated by Django 4.2.3 on 2025-01-19 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0008_order_detailed_snapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(verbose_name='ID товара')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Телефон анонимного пользователя')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время заказа')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quick_orders', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
