# Generated by Django 5.2.1 on 2025-12-23 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_quickorder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Корзина клиента', 'verbose_name_plural': 'Корзины клиентов'},
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'Товар в корзине', 'verbose_name_plural': 'Товары в корзинах'},
        ),
        migrations.AlterModelOptions(
            name='customerprofile',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='quickorder',
            options={'verbose_name': 'Быстрый заказ', 'verbose_name_plural': 'Быстрые заказы'},
        ),
    ]
